language:
script: zip worshipsongs.zip worship/*.onsong worship-swedish/*.onsong
deploy:
  provider: releases
  api_key:
    secure: rH08UrsJlhMPO/fXjeelHbSaxpzX+1EuNj5qyrbpqUlzfOq5BaPvHM0b2Q5ajFDRj5mQZOavImuV1mFeQeRShPUVlFM9DDj37G4U8lI/uafiBZs3xqGplSjneaDnRHpN9+FCN81tbx+x+Wu7T2+gqGwe9W8bzAXt7DDTyiv7S48Etwe6r0q+mCQVwHlJRAPDFaFj93f8IixQzXHejaDtYvz0RyTyiDkY+POAwfuo1lap/3gTCcOojLgstySUxzCckZp5AFT7dnyuXy/Yxh6UvOoZy3KSIZ/juHbc1W16Wv+HVmVVZtdSRmtbmLiD8hahzj3xqS+SwtzknvtD0i8dxt3l56gdw8gJtJMFfhqq/AMoBQqx++gGCII2oSRAKXskcpZ+8fPdHh0bUDCb79Sgpp38VeCAQTAgFJPzahcISp1LBCGHztfBNvehufyHI0NfB3kD+r87S88b2Rr6/ADpZhk9NKvqpOcvibCmn6nJ4z0zuNXOTdFiBuYXfyfynb/EP2XXvRpz1oGPW/YXYRNntkxzbbHGS4jUhlhQ6EmlsE5HvMAS7fFnYr88uo5rLaUvvt3cIWwmsdCcInUtxEJViSHemjx3qIJ8I+9HRr+64CgOXq0WZQhS1C+j7rPtZOnz6WvybXCkCPDQFl+OdO2h6VAyke+9kaqVbe4ucUxMSQM=
  file: worshipsongs.zip
  on:
    repo: jswetzen/worship-combination
  skip_cleanup: 'true'
