language:
script: zip worshipsongs.zip worship/*.onsong worship-swedish/*.onsong
deploy:
  provider: releases
  api_key:
    secure: o6bb4NjEe/87KSPNPddwH7hOAzxpylCqHJzF+cwfXenuYIaaKFs3SlSn1MOeSCClZO6536PnEWVSDn+iBAugwjSXhiWGm2L69LPp9fY6LBjgYebvLOMbdRiuuY5Os/bAXd5TPY8tkMQ+R7sGDRg0SdtT1OeIA1CJufUEO4QT7cJxgY1N7tv8EBZmGG/TPJ/e42GxPg0Wf+fjvQw43nMSSR1VSbVMALJA09ciDCLLyeQVz161kKi+ynyl0xfcs6Da14ocGp4WGFhcc3rrT3uOFi16Y4GflACHSy1SS4Uq7gMOVFTjMdCWeHBDljsYBCA5sOKT8Yt/RxwT8FtXKLZp1UBkrTjj6bcTbkGd7MB1UCT8hMuJMGy3NpDCyaO/pmJRtYzUtxRBTwR3/jKuun7Qgtc1qMXJMpYf54o0JzuV27IbuAelZQqLGH9sl6tiIRlGsT+OMPyTeLZBMZa/NHb1jNheGpTjU41+mr2ted4TwkHzgZ3kmdkiZNNU1KFw2/CqKGmYd2XeIWlZ8wIVAkikXYTkZyNm3sFF0cMhsxPSsWoMqozw0akdTZwXP8UPcfAB/1/Pt0rAdoVHWy34ukiu2ay8K1Ubs3MnbxM7F6l+JZjVMLz8BbH284azKjtv4m9KhwDMk3RoCj37cbNe327LLu+8qG2DIc+XNqetemsWXgU=
  file: worshipsongs.zip
  on:
    repo: jswetzen/worship-combination
    branch: master
  skip_cleanup: 'true'
